import {
  Activity,
  BarChart3,
  BookOpen,
  Bot,
  Briefcase,
  Calendar,
  FileImage,
  Frame,
  GalleryVerticalEnd,
  GraduationCap,
  HardHat,
  HeartHandshake,
  Home,
  LayoutDashboard,
  Leaf,
  Map,
  MapPin,
  MessageCircle,
  PieChart,
  Settings2,
  Shield,
  ShieldAlert,
  Sprout,
  SquareTerminal,
  Tractor,
  Truck,
  User,
  Users,
} from "lucide-react"

export const menuData = {
  user: {
    name: "Admin User",
    email: "admin@wri-indonesia.org",
    avatar: "https://ui.shadcn.com/avatars/01.png",
  },
  teams: [
    {
      name: "WRI Indonesia",
      logo: GalleryVerticalEnd,
      plan: "Smallholder HUB",
    },
  ],
  navMain: [
    {
      title: "Dashboard",
      url: "/dashboard-restricted/dashboard",
      icon: PieChart,
      items: [
        { title: "Basic KPI", url: "/dashboard-restricted/dashboard/basic-kpi", icon: BarChart3 },
        { title: "Farmer & Land Parcel", url: "/dashboard-restricted/dashboard/farmer-land-parcel", icon: Sprout },
        { title: "Training", url: "/dashboard-restricted/dashboard/training", icon: GraduationCap },
        { title: "BMP", url: "/dashboard-restricted/dashboard/bmp", icon: Leaf },
        { title: "HCV", url: "/dashboard-restricted/dashboard/hcv", icon: ShieldAlert },
        { title: "HSE", url: "/dashboard-restricted/dashboard/hse", icon: HardHat },
        { title: "Supply Chain", url: "/dashboard-restricted/dashboard/supply-chain", icon: Truck },
        { title: "Risk Management", url: "/dashboard-restricted/dashboard/risk-management", icon: Shield },
        { title: "BusDev", url: "/dashboard-restricted/dashboard/busdev", icon: Briefcase },
        { title: "GEDSI", url: "/dashboard-restricted/dashboard/gedsi", icon: HeartHandshake },
        { title: "Interactive Map", url: "/dashboard-restricted/dashboard/interactive-map", icon: Map },
      ],
    },
    {
      title: "Report",
      url: "/dashboard-restricted/report",
      icon: BookOpen,
      items: [
        { title: "Basic KPI", url: "/dashboard-restricted/report/basic-kpi", icon: BarChart3 },
        { title: "Farmer & Land Parcel", url: "/dashboard-restricted/report/farmer-land-parcel", icon: Sprout },
        { title: "Training", url: "/dashboard-restricted/report/training", icon: GraduationCap },
        { title: "BMP", url: "/dashboard-restricted/report/bmp", icon: Leaf },
        { title: "HCV", url: "/dashboard-restricted/report/hcv", icon: ShieldAlert },
        { title: "HSE", url: "/dashboard-restricted/report/hse", icon: HardHat },
        { title: "Supply Chain", url: "/dashboard-restricted/report/supply-chain", icon: Truck },
        { title: "Risk Management", url: "/dashboard-restricted/report/risk-management", icon: Shield },
        { title: "BusDev", url: "/dashboard-restricted/report/busdev", icon: Briefcase },
        { title: "GEDSI", url: "/dashboard-restricted/report/gedsi", icon: HeartHandshake },
        { title: "Interactive Map", url: "/dashboard-restricted/report/interactive-map", icon: Map },
      ],
    },
    {
      title: "Master Data",
      url: "/master-data",
      icon: SquareTerminal,
      items: [
        { title: "Farmer Groups", url: "/master-data/farmer-groups", icon: Tractor },
      ],
    },

    {
      title: "CMS",
      url: "/dashboard-restricted/cms",
      icon: Frame,
      items: [
        { title: "Home", url: "/dashboard-restricted/cms/home", icon: Home },
        { title: "Community", url: "/dashboard-restricted/cms/community", icon: MessageCircle },
        { title: "Activity", url: "/dashboard-restricted/cms/activity", icon: Calendar },
        { title: "Media", url: "/dashboard-restricted/cms/media", icon: FileImage },
      ],
    },
    {
      title: "Settings",
      url: "/master-data/settings", 
      icon: Settings2,
      items: [
        { title: "Provinces", url: "/master-data/provinces", icon: Map },
        { title: "Districts", url: "/master-data/districts", icon: MapPin },
        { title: "Groups", url: "/master-data/groups", icon: Users },
        { title: "Users", url: "/master-data/users", icon: User },
      ],
    },
  ],
  navSecondary: [
    {
        title: "Management User",
        url: "/dashboard-restricted/users",
        icon: Bot,
    },
    {
      title: "Settings",
      url: "/dashboard-restricted/settings",
      icon: Settings2,
    },
  ],
  projects: [], 
}
